// This file is auto-generated by scripts/generate-photos-manifest.mjs
// Do not edit by hand.

export type Photo = {
  src: string;
  width: number;
  height: number;
  alt: string;
};

export const photos: Photo[] = [
  {
    src: "/photos/DSC00027.jpg",
    width: 2017,
    height: 3025,
    alt: "DSC00027"
  },
  {
    src: "/photos/DSC00172.jpg",
    width: 4128,
    height: 6033,
    alt: "DSC00172"
  },
  {
    src: "/photos/DSC00542.jpg",
    width: 6062,
    height: 3672,
    alt: "DSC00542"
  },
  {
    src: "/photos/DSC00638.jpg",
    width: 6020,
    height: 4012,
    alt: "DSC00638"
  },
  {
    src: "/photos/DSC00831.jpg",
    width: 2048,
    height: 1365,
    alt: "DSC00831"
  },
  {
    src: "/photos/DSC00846.jpg",
    width: 2048,
    height: 1365,
    alt: "DSC00846"
  },
  {
    src: "/photos/DSC00866.jpg",
    width: 2048,
    height: 1365,
    alt: "DSC00866"
  },
  {
    src: "/photos/DSC01482.ARW.jpg",
    width: 6192,
    height: 4128,
    alt: "DSC01482.ARW"
  },
  {
    src: "/photos/DSC03052.jpg",
    width: 2048,
    height: 1365,
    alt: "DSC03052"
  },
  {
    src: "/photos/DSC03382-3.jpg",
    width: 2048,
    height: 1365,
    alt: "DSC03382 3"
  },
  {
    src: "/photos/DSC03401.jpg",
    width: 2048,
    height: 1365,
    alt: "DSC03401"
  },
  {
    src: "/photos/DSC03691.jpg",
    width: 2048,
    height: 1307,
    alt: "DSC03691"
  },
  {
    src: "/photos/DSC03696.jpg",
    width: 2048,
    height: 1365,
    alt: "DSC03696"
  },
  {
    src: "/photos/DSC03886.jpg",
    width: 2048,
    height: 1365,
    alt: "DSC03886"
  },
  {
    src: "/photos/DSC03888.jpg",
    width: 2048,
    height: 1365,
    alt: "DSC03888"
  },
  {
    src: "/photos/DSC03987.jpg",
    width: 2048,
    height: 1365,
    alt: "DSC03987"
  },
  {
    src: "/photos/DSC04026-2.jpg",
    width: 1365,
    height: 2048,
    alt: "DSC04026 2"
  },
  {
    src: "/photos/DSC04074.jpg",
    width: 2048,
    height: 1365,
    alt: "DSC04074"
  },
  {
    src: "/photos/DSC04084.jpg",
    width: 2048,
    height: 1365,
    alt: "DSC04084"
  },
  {
    src: "/photos/DSC05162.jpg",
    width: 3042,
    height: 1904,
    alt: "DSC05162"
  },
  {
    src: "/photos/DSC07011.jpg",
    width: 3827,
    height: 5875,
    alt: "DSC07011"
  },
  {
    src: "/photos/DSC07187.jpg",
    width: 1989,
    height: 2985,
    alt: "DSC07187"
  },
  {
    src: "/photos/DSC07405.jpg",
    width: 3867,
    height: 5963,
    alt: "DSC07405"
  },
  {
    src: "/photos/DSC07529 copy.jpg",
    width: 6076,
    height: 4050,
    alt: "DSC07529 copy"
  },
  {
    src: "/photos/DSC07553.jpg",
    width: 6192,
    height: 4128,
    alt: "DSC07553"
  },
  {
    src: "/photos/DSC07562.jpg",
    width: 6060,
    height: 4040,
    alt: "DSC07562"
  },
  {
    src: "/photos/DSC07587.jpg",
    width: 5984,
    height: 4032,
    alt: "DSC07587"
  },
  {
    src: "/photos/DSC07631 Large.png",
    width: 1280,
    height: 853,
    alt: "DSC07631 Large"
  },
  {
    src: "/photos/DSC07702.jpg",
    width: 5547,
    height: 3768,
    alt: "DSC07702"
  },
  {
    src: "/photos/DSC07748.jpg",
    width: 3953,
    height: 6192,
    alt: "DSC07748"
  },
  {
    src: "/photos/DSC07802.jpg",
    width: 4128,
    height: 6192,
    alt: "DSC07802"
  },
  {
    src: "/photos/DSC07816.jpg",
    width: 6034,
    height: 3802,
    alt: "DSC07816"
  },
  {
    src: "/photos/DSC08001.jpg",
    width: 6192,
    height: 4128,
    alt: "DSC08001"
  },
  {
    src: "/photos/DSC08526.jpg",
    width: 2064,
    height: 3096,
    alt: "DSC08526"
  },
  {
    src: "/photos/DSC08656.jpg",
    width: 1974,
    height: 2962,
    alt: "DSC08656"
  },
  {
    src: "/photos/DSC09980.jpg",
    width: 1821,
    height: 2428,
    alt: "DSC09980"
  },
  {
    src: "/photos/linkage.jpg",
    width: 6048,
    height: 4032,
    alt: "linkage"
  },
  {
    src: "/photos/ph.jpg",
    width: 3096,
    height: 1449,
    alt: "ph"
  },
  {
    src: "/photos/phot.jpg",
    width: 3981,
    height: 5971,
    alt: "phot"
  }
] as const;
